### PR TITLE
my implementation of a file acl module

### PR DESCRIPTION
**Pull request by b6d**
Hello,

a while ago, I intended to propose a few changes to Ansible's ACL-module. I based these on the version in release 1.4.4 since I had troubles using the devel-branch at the time.

Since then, Ansible's acl-module has changed quite a bit, and my changes are not compatible any more. However, maybe my version of the module can still provide a little input - this is why I send this request. (this is neither intended to exist alongside the current acl module, nor to replace it)

PS: Unfortunately, I wrongly sent an unfinished version of this pull request to ansible/ansible instead of bcoca/ansible about an hour ago. This was not intended, and I apologize for any confusion.

**A few comments regarding the module**
- Main goal was to allow multiple entries instead of a single one while retaining compatibility to the (then) current form of the module. There are two reasons behind this: First, default ACL entries can (afaik) only be removed, if all three of them are removed. Second, I often have loops over several directories we want to set ACLs to, and I wanted to avoid an inner loop for setting all entries of a single directory.
- Another thing I wanted was to be able to specify a complete ACL and have the module set this ACL exactly - in other words, entries not specified should not be in the ACL after the module has run. This can be done by supplying remove_unspecified=yes
- The module relies heavily on the GNU implementation of setfacl (the one that came packaged with ubuntu 12.04). I suspect you use a different one, since my setfacl does not understand the parameter "-h" as yours seems to (follow symlinks).
- Always anticipating changes correctly for check_mode=True seems not as straightforward as I had hoped, especially when supplying multiple ACL entries. After I failed replicating setfacl's logic regarding this in a simple, easily understandable way, I decided to let setfacl do the checking (setfacl --test) and evaluate it's results. This seems to work nicely, at least with my version of setfacl.
- I tried to have internal representations of ACL entries (Keys and Permissions). An ACL in the module is then a dict  of Keys mapping to Permissions.
- I tried to parse ACL entries via regex, it should hopefully interpret them the same way as setfacl.
- A parameter to purge the complete ACL was added (state=empty)
- The module is not well-tested at the moment

I hope that one or the other fragment of my acl-implementation can be useful in the further development of Ansible's ACL module

regards,

Bernhard

### CODE REVIEW

**Comment by bcoca** [comment]
hi, I appreciate the feedback and contribution.

#1) I avoided doing multiple entries in a single invocation as it complicated the code a lot, I left it up to the user and with_items: 

#2) The updated module does something very close to this, it just always uses the long form of an entry.

#3) Not really, relies mostly on FreeBSD implementation (which is what I was using at the time), since the command is not in Posix standards it might vary (I've tested on Gentoo, Ubuntu and Debian also). The -h was a typo, I need to remove it. It was a placeholder for when I was still contemplating the recursive function.

#4) yep, this one is not as easy as one would think, the last version does a much better job now. I doubt I'll be changing as --test is not available on all setfacl binaries I have used.

#5) this is what the posix1e module already does, but I was asked not to use it to reduce dependencies and in the end it is simpler code.

#6) I do string matching on the first character, the result is the same.

#7) we already have that with the using the ansible convention state=absent

#8) that is what production is for! kidding aside, I have a few minor tests I haven't pushed to the main repo yet, they aren't perfect but it is a start.

Just to point out, I'm not an ansible maintainer, just the module author, discussion or ideas on how to enhance ansible might be better on the ansible-devel mailing list (google group). At least there you'll get more opinions than just mine (also that is where the guys with commit privileges to ansible proper will be).

**Comment by b6d** [comment]
Thanks for your quick reply,

I'm looking forward to the acl-module in Ansible 1.5

**Comment by bcoca** [comment]
We might be able to implement a  'clear all and insert this' with:

   -b        Remove all ACL entries except for the three required entries

just might be a bit complicated with 'changed' status

**Comment by bcoca** [comment]
closing this as I moved the conversation to ansible-devel

**Pull request closed without merging**
